### ISSUE TITLE
Outdated Pimple version

### ISSUE THREAD

**Issue by Rarst** [mnapoli/silly-pimple#1]
Hi!

Silly [documentation recommends this package](https://github.com/mnapoli/silly/blob/master/docs/pimple.md) as Pimple build, but it's notably outdated:
- required Pimple v1 is two major versions behind current v3
- Pimple comes with [native PSR-11 adapter](https://github.com/silexphp/Pimple#psr-11-compatibility) now 

Would you be interested in keeping/updating this package?.. Or maybe dropping separate package altogether in favor of updating docs to just use Pimple's PSR-11 support?

I could tinker on either, if you let me know what is preferable. :)

**Comment by mnapoli** [comment]
Hi, thanks for opening this issue.

> Or maybe dropping separate package altogether in favor of updating docs to just use Pimple's PSR-11 support?

That sounds like a better option!
